export default [
    {
        id: "umvl9mmtwdcwh8f1rpg94umvl9u2zrf8",
        fullName: "Dmytro P.",
        position: "Backend Developer",
        experience: "5 - 10 years",
        tags: ["Node.js", "TypeScript", "Kotlin"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Seasoned backend developer, fluent in multiple languages and platforms, no stranger to the trending practices",
        linkedin: "https://www.linkedin.com/in/dmytro-petrovych-74256153",
        github: "https://github.com/dpetrovych",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "vhn5kbrj7evswv75dh3zohwc3p8c8x17",
        fullName: "Charujan T.",
        position: "Fullstack Developer",
        experience: "3 - 5 years",
        tags: ["Node.js", "TypeScript", "Kotlin"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction:
            "Fullstack Developer (backend oriented) with good knowledge on the payment domain.",
        linkedin: "https://www.linkedin.com/in/charujan-thavendran-03b870a5/",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "vkn4x3v558dsg1n0w21vkn4x475dd497",
        fullName: "Abdelhakim B.",
        position: "Data Scientist/Software Engineer",
        experience: "3 - 5 years",
        tags: ["Machine Learning", "Python", "ETL"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction: "",
        linkedin: "https://www.linkedin.com/in/abdelhakimbendjabeur/",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "rm4iob83u5fpgc0ebzxqrm4e8skhk6cb",
        fullName: "Claire B.",
        position: "Lead Product Manager",
        experience: "5 - 10 years",
        tags: ["Product Strategy", "Data Driven", "Leadership"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Loved discovering and growing B2C/B2B products for Kapten customers 😍. Looking for a 1st product position in a startup or a senior role in a scale-up.",
        linkedin: "https://www.linkedin.com/in/claireboitrel/",
        github: "",
        personalWebsite: "",
        department: "Product",
    },
    {
        id: "06zdnov5v06zdsw9rlnb54xc052sw9f1",
        fullName: "Vincent S.",
        position: "Fullstack Developer",
        experience: "5 - 10 years",
        tags: ["Software Architect", "Continuous Integration", "Empathy"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "I've provided B2B features for company and their users.I was spreading good practice code architecture over the teams, be always open mind to try new tools and improve our daily work. I was the TypeScript Mentor of the stack and Node.js guild master.",
        linkedin: "https://www.linkedin.com/in/vincentschoener",
        github: "http://github.com/vschoener",
        personalWebsite: "http://www.vincelivemix.fr",
        department: "Engineering",
    },
    // {
    //     id: "wyrcc9omymdda0jowyrcczr8uvsgkdwh",
    //     fullName: "Jérôme G",
    //     position: "Tribe Director",
    //     experience: "> 10 years",
    //     tags: ["Node.js", "Python", "Management"],
    //     location: "Nantes",
    //     isOpenToRelocationOrRemote: true,
    //     introduction:
    //         "Engineering Director building and running multidisciplinary teams.",
    //     linkedin: "https://www.linkedin.com/in/jeromegrondin/",
    //     github: "https://github.com/jerome-cp",
    //     personalWebsite: "",
    //     department: "Engineering",
    // },
    // {
    //     id: "c94oq9iyc916yd7ymqc94o50yt7zwiya",
    //     fullName: "Aude F.",
    //     position: "Backend Developer",
    //     experience: "1 - 3 years",
    //     tags: ["Node.js", "TypeScript", "Kotlin", "NoSQL", "Unit tests"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: true,
    //     introduction:
    //         "Back-end developper reconverted from acoustic consultant. I like technical challenges and always learn new things",
    //     linkedin: "https://fr.linkedin.com/in/aude-falco",
    //     github: "https://github.com/Aud123",
    //     personalWebsite: "",
    //     department: "Engineering",
    // },
    {
        id: "beva71rwp40ggn17gfckvbeva71rqrsf",
        fullName: "Imen A.",
        position: "Fullstack Developer",
        experience: "5 - 10 years",
        tags: ["Node.js", "React", "Golang"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Software engineer with 5 years and a half of experience. Worked on multiple new frameworks and tools in different coding languages. Grew in different teams from a developer to a lead, speaker and a mentor.",
        linkedin: "https://www.linkedin.com/in/imen-ammar/",
        github: "https://github.com/ImenAmmar",
        personalWebsite: "",
        department: "Engineering",
    },
    // {
    //     id: "xmi6dt39239xmi6dbg19e84o17gffhbg",
    //     fullName: "Farzad F.",
    //     position: "Infrastructure & Operations Manager",
    //     experience: "> 10 years",
    //     tags: ["Leadership", "Infrastructure as Code", "SRE"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: false,
    //     introduction:
    //         "Senior IT Manager, SRE, DevOps practitioner, IT architect and consultant, with more than 25 years of field experience",
    //     linkedin: "https://www.linkedin.com/in/ffarid/",
    //     github: "https://github.com/Farzy/",
    //     personalWebsite: "https://farzy.org",
    //     department: "Engineering",
    // },
    {
        id: "nzatjgzt4mt9wor7ynzatju7b391cqrk",
        fullName: "Hélène D.",
        position: "Lead Developer",
        experience: "3 - 5 years",
        tags: ["Node.js", "MongoDB"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "4 years as a Backend Developer and then as a Lead Developer, mainly in a Node.js environment, I am now highly motivated to find my next adventure in a company with which I share the values and that I can help grow.",
        linkedin:
            "https://www.linkedin.com/in/h%C3%A9l%C3%A8ne-droal-66703b60/",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "7u4p33ot5oq4dijz8a8lc87u4p333a1f",
        fullName: "Jean-Guillaume B.",
        position: "Network and Systems Technician",
        experience: "5 - 10 years",
        tags: ["Helpdesk", "System"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction: "Helpdesk experience for 7 years",
        linkedin: "http://linkedin.com/in/jbouchez",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "xymbdhbr9ebg3pcp8xym0j3x4lazbay8",
        fullName: "Jean-Christophe M.",
        position: "IOS Developer",
        experience: "5 - 10 years",
        tags: ["IOS", "Swift"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "iOS developer (old fullstack) looking for a new challenge on an innovating project",
        linkedin: "https://www.linkedin.com/in/jcmougamadou/",
        github: "https://github.com/jcmougamadou",
        personalWebsite: "https://twitter.com/jcmougamadou",
        department: "Engineering",
    },
    {
        id: "ustkhfwdozvcwng62a7ustkhw01l77hw",
        fullName: "Didier Z.",
        position: "Lead Developer",
        experience: "> 10 years",
        tags: ["Node.js", "Java"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction: "Lead Dev with strong experience in backend dev",
        linkedin: "https://www.linkedin.com/in/didinginfojava-7b074684",
        github: "https://github.com/raizec",
        personalWebsite: "",
        department: "Engineering",
    },
    //{
    //    id: "d7t0s885g0308j8ig3dd7t0mttk0pxev",
    //    fullName: "Céline B.",
    //    position: "Backend Developer",
    //    experience: "3 - 5 years",
    //    tags: ["Kotlin", "Node.js", "Go"],
    //    location: "Paris",
    //    isOpenToRelocationOrRemote: true,
    //    introduction:
    //        "Back-end developer with experience in internationalised payment and invoicing systems",
    //    linkedin: "https://www.linkedin.com/in/crjbrunet/",
    //    github: "https://github.com/celinebrunet",
    //    personalWebsite: "",
    //    department: "Engineering",
    //},
    {
        id: "l0ohykw6lkumnpdoppc3qbqf4l0ohykw",
        fullName: "Rémy G.",
        position: "Backend Developer",
        experience: "5 - 10 years",
        tags: ["Javascript", "PHP", "TDD"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Backend engineer, DDD and hexagonal architecture lover. Love solving problems. Curious about everything about computer programming. Look for freelance jobs 🙏",
        linkedin: "https://www.linkedin.com/in/remygouello/",
        github: "https://github.com/KinderGouello",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "6y11d0249qtd1m1xhnxa6y11d02s3sfz",
        fullName: "Joana C.",
        position: "Backend Developer",
        experience: "5 - 10 years",
        tags: ["Node.js", "MongoDB"],
        location: "Full remote",
        isOpenToRelocationOrRemote: true,
        introduction: "Backend dev willing to build a better world",
        linkedin: "https://fr.linkedin.com/in/joana-costa-5526a026",
        github: "https://github.com/joana-costa",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "hl4840cna4y7g6rhhl4840x3s64pfu02",
        fullName: "Antonin B.",
        position: "Backend Developer",
        experience: "1 - 3 years",
        tags: ["Backend", "Node.js", "Tooling"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Backend developer, driven by learning and solving technical problems. I'm currently working on devops tools facilitating developers workflow and services deployments.",
        linkedin: "https://linkedin.com/in/antonin-blin",
        github: "https://github.com/Antoninbln",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "rtsi6sv604ypr69rtsi6s8gsxpkaev5w",
        fullName: "Florent M.",
        position: "UX Researcher",
        experience: "3 - 5 years",
        tags: ["Interviews", "User tests", "Product Design"],
        location: "Barcelona",
        isOpenToRelocationOrRemote: false,
        introduction:
            "My goal is to drive product innovation and business decisions through research insights while implementing UX Research best practices.",
        linkedin: "https://www.linkedin.com/in/florentmartinez/",
        github: "",
        personalWebsite: "https://florent-martinez.com/",
        department: "Product",
    },
    {
        id: "8guf69phs479ac6ez8guf6dyx7s22a8f",
        fullName: "Fabien L.",
        position: "Product Specialist",
        experience: "3 - 5 years",
        tags: ["Troubleshooting", "Data Analysis", "Case Management"],
        location: "London",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Experienced data driver Product Specialist looking for new challenges as Product Analyst or Product Manager.",
        linkedin: "https://www.linkedin.com/in/fabien-lavaud-856833116/",
        github: "",
        personalWebsite: "",
        department: "Product",
    },
    {
        id: "cfxcz78c79i9151cfongt1sl96rmabck",
        fullName: "Razvan L.",
        position: "Backend Developer",
        experience: "3 - 5 years",
        tags: ["Node.js", "Back-end", "API"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Experienced Node.js back-end with super fast pace learning curve",
        linkedin: "https://www.linkedin.com/in/razvan-ludosanu/",
        github: "https://github.com/rludosanu",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "p37hyp87qoo7whjp37hocc3nkdobov5j",
        fullName: "Enzo M.",
        position: "Product Manager",
        experience: "1 - 3 years",
        tags: ["Data Oriented", "Mobile", "Growth"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction:
            "B2B & Growth PM with 2 years experience looking for a product position in a start-up or scale-up.",
        linkedin: "https://www.linkedin.com/in/enzo-mathe/",
        github: "",
        personalWebsite: "",
        department: "Product",
    },
    {
        id: "tbhsd25tnujmhstbgcfb4qjciprc38bz",
        fullName: "Olivier W.",
        position: "Product Manager",
        experience: "3 - 5 years",
        tags: ["Product", "UX", "Scale"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction:
            "Enthusiast product manager seeking to make an impact in your product. Have proven record of scaling tech products - Just ask!",
        linkedin: "https://www.linkedin.com/in/olivierwojdyniak/",
        github: "",
        personalWebsite: "",
        department: "Product",
    },
    {
        id: "si91n68thzjxmam949cmsi91n68rolrz",
        fullName: "Emilie O.",
        position: "Lead Product Specialist",
        experience: "0 - 1 year",
        tags: ["Troubleshooting", "SQL", "Team Management"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            'Lead of the "bug killer" team with a 2 years experience in Customer Support mixed with a strong taste for Product',
        linkedin: "https://www.linkedin.com/in/emilie-ond/",
        github: "",
        personalWebsite: "https://www.instagram.com/emilieond",
        department: "Product",
    },
    // {
    //     id: "wiutx9243bsmy2nlcwwiuusqkgohdel2",
    //     fullName: "Alice T.",
    //     position: "Data Analyst",
    //     experience: "0 - 1 year",
    //     tags: ["SQL", "Tableau"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: false,
    //     introduction:
    //         "Data analyst with experience conducting complex analyses and building robust BI dashboards",
    //     linkedin: "https://www.linkedin.com/in/alicetriquet/",
    //     github: "",
    //     personalWebsite: "",
    //     department: "Engineering",
    // },
    {
        id: "jtuowv7wy4nw04rwamjtuow0cxppj375",
        fullName: "Aya E.",
        position: "Data Analyst",
        experience: "1 - 3 years",
        tags: ["Python", "SQL", "R", "Machine Learning"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction:
            "Experienced Data Analyst with an appetite for machine learning",
        linkedin: "https://www.linkedin.com/in/ayaesaki/",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    // {
    //     id: "266qbgm2g20ykpqx3f9v3266q0bf4p9q",
    //     fullName: "Florent V.",
    //     position: "Fullstack Developer",
    //     experience: "1 - 3 years",
    //     tags: ["React", "Typescript", "ES2020"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: false,
    //     introduction:
    //         "Fullstack developer with a strong focus on building quality user interfaces using React. Driven by challenge, I love my job as much as climbing mountains and surfing waves on my spare time 🤙🏼",
    //     linkedin: "https://fr.linkedin.com/in/florent-violin",
    //     github: "https://github.com/Flovln",
    //     personalWebsite: "",
    //     department: "Engineering",
    // },
    {
        id: "i9nawemfgif6yduhq8i9nawespoz1wct",
        fullName: "Fatimata S.",
        position: "Lead Analytics",
        experience: "5 - 10 years",
        tags: ["Business oriented", "Team Management", "SQL"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction:
            "Analytics girl always willing to empower business teams and spread a data-driven culture among companies. (5+ years of experience in data consulting and data analytics)",
        linkedin: "https://www.linkedin.com/in/fatimata-sall-03/",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "2tnisqfx75fg1y632tnisdcp8ibfotuw",
        fullName: "Steven H.",
        position: "Backend Developer",
        experience: "1 - 3 years",
        tags: ["Node.js", "MongoDB", "Backend"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "As a junior developer, I'm looking for a place where I can learn and grow as a back-end developer. I am not closed to learning new languages, I can quickly assimilate other technology if needed.",
        linkedin: "https://www.linkedin.com/in/hengsteven/",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "s53vziy7nexcmgdz7s53vzfd0qs62qhh",
        fullName: "Thao T.",
        position: "Fullstack Developer",
        experience: "1 - 3 years",
        tags: ["Node.js", "React", "Java"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction:
            "Young, enthusiastic fullstack developer hunting for challenges",
        linkedin: "https://www.linkedin.com/in/thach-thao-tran-102a5693/",
        github: "https://github.com/ZickyChan",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "ewu6w6cynr6gqs2r296xpopeewu6w6s6",
        fullName: "Etienne B.",
        position: "Backend Developer",
        experience: "3 - 5 years",
        tags: ["Node.js", "Typescript", "Kotlin"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction:
            "Experienced Node.js backend developer ready for a new adventure in a fast growing company",
        linkedin: "https://www.linkedin.com/in/etienne-bourdos/",
        github: "https://github.com/EtienneBourdos",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "kgyiyhq8tiaw8315ct68kgyiy5xhhvyo",
        fullName: "Tissayme K.",
        position: "HR Officer",
        experience: "3 - 5 years",
        tags: ["Paie", "Administration du Personnel", "Généraliste"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "5 years as a HR officer and as a Payroll and Administration Officer in growing companies and start-ups. I am available to be in charge of payroll, personnel administration, training and other HR projects.",
        linkedin: "https://www.linkedin.com/in/tissaymektoul/",
        github: "",
        personalWebsite: "",
        department: "Human Ressources",
    },
    {
        id: "s5jjaz6s0nzorbf3lits5jjaz6s4hiz8",
        fullName: "Driss D.",
        position: "Data Scientist/Software Engineer",
        experience: "1 - 3 years",
        tags: ["Python", "ETL", "Machine learning"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction: "Looking to build and deploy end-to-end ML models.",
        linkedin: "https://linkedin.com/in/driss-debbagh-nour-b81463108",
        github: "https://github.com/Driss31",
        personalWebsite: "",
        department: "Engineering",
    },
    // {
    //     id: "nm5e6xz4s5yl24wa9wd1nm5e6z5psjg7",
    //     fullName: "Guillaume B.",
    //     position: "Fullstack Developer",
    //     experience: "1 - 3 years",
    //     tags: ["Node.js", "React", "Typescript"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: false,
    //     introduction:
    //         "A developer who enjoys writing robust services and working in team.",
    //     linkedin: "https://www.linkedin.com/in/guillaume-benard/",
    //     github: "https://github.com/benard-g",
    //     personalWebsite: "",
    //     department: "Engineering",
    // },
    {
        id: "ky63pnf906hdjjc6kyazs7bdtymcjav5",
        fullName: "Aymeric S.",
        position: "Fullstack Developer",
        experience: "3 - 5 years",
        tags: ["Node.js", "Typescript", "MongoDB"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Full-stack developer with a focus in Node.js, working in the client experience domain. Very curious about anything, and love working in a fast growing environment.",
        linkedin: "https://www.linkedin.com/in/aymericsecret/",
        github: "https://github.com/aymericsecret",
        personalWebsite: "",
        department: "Engineering",
    },
    // {
    //     id: "2pn8b83tgpeegf6p392pn8b8frys1s4z",
    //     fullName: "Kristen L.",
    //     position: "Lead Developer",
    //     experience: "> 10 years",
    //     tags: ["Engineering", "Management", "Product driven"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: true,
    //     introduction:
    //         "Squad lead with a strong experience in development, training, algorithms and problem solving.",
    //     linkedin: "https://www.linkedin.com/mwlite/in/kristenleliboux",
    //     github: "",
    //     personalWebsite: "",
    //     department: "Engineering",
    // },
    // {
    //     id: "kyhuuyxlzsfug65kyhuuyo9w00jrpmpn",
    //     fullName: "Manon R.",
    //     position: "Office Manager",
    //     experience: "1 - 3 years",
    //     tags: ["Event planning", "Services généraux", "Communication interne"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: false,
    //     introduction:
    //         "Office Manager & Happiness Officer looking for a company with good human values and lots of projects to take on !",
    //     linkedin: "https://www.linkedin.com/in/manon-racz-1a34b089/",
    //     github: "",
    //     personalWebsite: "",
    //     department: "Human Ressources",
    // },
    // {
    //     id: "dmjwm2oizkvxuazm5p900wdmjwm25hni",
    //     fullName: "Guillaume D.",
    //     position: "Product Manager",
    //     experience: "1 - 3 years",
    //     tags: ["Product Strategy", "Data Driven", "Customer Centric"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: false,
    //     introduction:
    //         "Product Manager driven by data, customer insight and passion. 3 years of experience in a super fast-paced environment. Looking for the next challenge!",
    //     linkedin: "https://www.linkedin.com/in/guillaumedenolle/",
    //     github: "",
    //     personalWebsite: "",
    //     department: "Product",
    // },
    {
        id: "dt96z6u99zgueea6gcdt96z6ur5xv39k",
        fullName: "Simon B.",
        position: "Data Science Team Lead",
        experience: "3 - 5 years",
        tags: ["MLOps", "Leadership", "Kubernetes"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "I lead teams that build and deploy machine learning models and data products to production.",
        linkedin: "https://www.linkedin.com/in/simonbensoussan",
        github: "https://github.com/sbensoussan",
        personalWebsite: "",
        department: "Engineering",
    },
    // {
    //     id: "a5mapbsft903ijo90a5mawpj71jj02l8",
    //     fullName: "Anne-Sophie L.",
    //     position: "Product Manager",
    //     experience: "3 - 5 years",
    //     tags: ["Data Science", "ML features", "Data Analysis"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: true,
    //     introduction:
    //         "Data Science PM, supporting a team of 6 DS with delivering real business impact through Machine Learning features",
    //     linkedin: "https://www.linkedin.com/in/anne-sophie-lavelle-1a94b480/",
    //     github: "",
    //     personalWebsite: "",
    //     department: "Product",
    // },
    // {
    //     id: "ciimm1j7da2x3pxxciimm12w1orpculq",
    //     fullName: "Hortense D.",
    //     position: "Technical recruiter",
    //     experience: "5 - 10 years",
    //     tags: ["Tech recruitment", "International processes"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: true,
    //     introduction:
    //         "I am a recruiter and I work on a daily basis with managers to build their teams.",
    //     linkedin: "http://linkedin.com/in/hortense-duclos",
    //     github: "",
    //     personalWebsite: "",
    //     department: "Human Ressources",
    // },
    {
        id: "i1absyxofiggdpwl9hmucxei1absyacg",
        fullName: "Jean-François G.",
        position: "Tribe Director",
        experience: "> 10 years",
        tags: ["Architecture", "Development best practices", "Leadership"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Passionate about people, technology and software development with 20+ years of experience, looking for new challenges in a fast and growing environment where people are valued.",
        linkedin: "https://www.linkedin.com/in/jeanfrancois-guyet",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "vf7btt0y5o3hs5d370vf7btfl6tjk20w",
        fullName: "Sokarlyane C.",
        position: "IT Engineer",
        experience: "> 10 years",
        tags: ["Project manager", "Infrastructure"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction: "Ensure the best users experience",
        linkedin: "https://www.linkedin.com/in/sokarlyane-chhuon-29315423/",
        github: "https://github.com",
        personalWebsite: "https://twitter.com/home",
        department: "Engineering",
    },
    {
        id: "db593nn44lxf3o5s7q80db59pa5xnjws",
        fullName: "Elodie L.",
        position: "Product Manager",
        experience: "1 - 3 years",
        tags: ["Analytical skills", "Data oriented"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Confirmed Product Manager who wants to contribute to an exciting and meaningful project",
        linkedin: "https://www.linkedin.com/in/elodie-lachoua-1b034094/",
        github: "",
        personalWebsite: "",
        department: "Product",
    },
    {
        id: "fqavzw7kvcq2rofqavzwdcuvmljm5mho",
        fullName: "Maxime R.",
        position: "Customer Service Agent",
        experience: "1 - 3 years",
        tags: ["Dynamic", "Warm", "Persuasive"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "I am in charge of customer relations and have been working in this field for almost 3 years.   I enjoy contact with the public and I have developed a strong sense of communication and customer contact through my experiences.",
        linkedin: "https://www.linkedin.com/in/maxime-roulleau-3686b3107/",
        github: "",
        personalWebsite: "",
        department: "Customer Service",
    },
    {
        id: "c5vevdaqpfh3qvrtp0ync5vevgmmuhed",
        fullName: "Benjamin B.",
        position: "Database Administrator",
        experience: "> 10 years",
        tags: ["MongoDB", "PostgreSQL", "Infrastructure-as-code"],
        location: "Remote",
        isOpenToRelocationOrRemote: true,
        introduction: "Database Architect/Administrator",
        linkedin: "https://www.linkedin.com/in/benbauer/",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    // {
    //     id: "83jvbckea1d3hc2083j6p1rx2nq16jfc",
    //     fullName: "Thomas T.",
    //     position: "Product Design Manager",
    //     experience: "5 - 10 years",
    //     tags: ["Coaching", "Design Strategy", "UX/UI"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: false,
    //     introduction:
    //         "Salut à toi jeune recruteur. Est-ce que tu préfères continuer à laisser ton équipe design se gérer toute seule ou confier cette tâche à quelqu'un dont c'est la spécialité? Moi je crois la question elle est vite répondue...",
    //     linkedin: "https://www.linkedin.com/in/thomas-tran-b8b4884b/",
    //     github: "",
    //     personalWebsite: "",
    //     department: "Product",
    // },
    {
        id: "qxwxi1w37rdfhm2edqxwxi1w3s9868eq",
        fullName: "Saâd D.",
        position: "Site Reliability Engineer",
        experience: "5 - 10 years",
        tags: ["Kubernetes", "GCP", "Terraform"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction:
            "Site Reliability Engineer with 9 years of experience in system, database and network operations",
        linkedin: "https://www.linkedin.com/in/saaddif/",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    // {
    //     id: "z8pllgc7iuqyodl60z8pll4vdxct55wn",
    //     fullName: "Kenny A.",
    //     position: "Fullstack Developer",
    //     experience: "3 - 5 years",
    //     tags: ["Node.js", "React", "Typescript", "Javascript"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: true,
    //     introduction: "",
    //     linkedin: "https://www.linkedin.com/in/kennyalvizuris/",
    //     github: "https://github.com/Kenny407",
    //     personalWebsite: "https://github.com/Kenny407",
    //     department: "Engineering",
    // },
    {
        id: "03jo9hde0jfiv7fh703jo9xdjd67xe3l",
        fullName: "Thomas D.",
        position: "Android Developer",
        experience: "5 - 10 years",
        tags: ["Android", "Kotlin"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Android developer (had previous backend experience) looking for",
        linkedin: "https://www.linkedin.com/in/thomas-depinoy-8706a971",
        github: "https://github.com/TDepinoy",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "5xikmubevioj3kupzkd5xikmudfutd05",
        fullName: "Benjamin D.",
        position: "Backend Developer",
        experience: "5 - 10 years",
        tags: ["React", "Rails", "Go"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Seasoned full stack developer looking for his next challenge. Dev and/or team leader position.",
        linkedin: "https://www.linkedin.com/in/benjamin-delmas/",
        github: "https://github.com/bdelmas",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "2rya2mukb0uncy64wreji2rya2mukgx0",
        fullName: "Thomas T.",
        position: "Quality Analyst",
        experience: "3 - 5 years",
        tags: ["Quality Assurance", "Testing", "BDD"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction: "",
        linkedin: "https://www.linkedin.com/in/thomas-toulet/",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "grnqfhvdljuf3ys8grnodrlgjdyx1lgu",
        fullName: "Louis L.",
        position: "Lead Developer",
        experience: "5 - 10 years",
        tags: ["Node.js", "MongoDB", "Management"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction:
            "Lead backend developer with strong focus on architecture and scalability. Contributed to make Kapten grow in the last 5 years with contributions such as fullstack development, project management, mentoring, hiring interviews, team and people management",
        linkedin: "https://www.linkedin.com/in/louis-ledey/",
        github: "https://github.com/lledey",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "oukq7ak6nql2zoroukqj284k9cwfupir",
        fullName: "Brahim F.",
        position: "Fullstack Developer",
        experience: "5 - 10 years",
        tags: ["Architecture", "Web Development", "Agile"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Looking for a new adventure in a progressivist company with a solid product vision, concrete values and a high degree of technical challenges",
        linkedin: "https://www.linkedin.com/in/brahim-foura-98757552/",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "za3smeshmblsxgbkza3smwse0jwgbqkp",
        fullName: "Nathan I.",
        position: "Lead Developer",
        experience: "3 - 5 years",
        tags: ["Node.js", "MongoDB", "MySQL"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Backend enthusiast, eager to tackle architecture and algorithmic challenges with great teammates!",
        linkedin: "https://fr.linkedin.com/in/nathan-irjud-306518a6",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "d2ndihh8q1h0gbtufd2ndi8yzz7uap3n",
        fullName: "Yassin E.",
        position: "IOS Developer",
        experience: "5 - 10 years",
        tags: ["Swift", "RxSwift", "MVVM-C", "Unit Tests"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction: "iOS Developper with 8 years experience",
        linkedin: "https://www.linkedin.com/in/yassin-el-mouden-85352163",
        github: "https://github.com/yelmouden",
        personalWebsite: "https://github.com/yelmouden",
        department: "Engineering",
    },
    {
        id: "kpcsxuzms6w60vljskpcsx1q2okl62jx",
        fullName: "Stephie A.",
        position: "Customer Service Agent",
        experience: "3 - 5 years",
        tags: ["Zendesk", "JIRA", "Management"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Longue expérience en service client dans les applications mobiles (ride-hailing, foodtech, bike sharing). Je cherche à me reconvertir en qualité de chef de projet.",
        linkedin: "https://fr.linkedin.com/in/stephie-abdelhaq-19477711a",
        github: "",
        personalWebsite: "",
        department: "Customer Service",
    },
    {
        id: "yljqkewwx6ix78j3rkyljqkeocof0zxh",
        fullName: "Mani R.",
        position: "Data Analyst",
        experience: "3 - 5 years",
        tags: ["Business", "Python", "SQl"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction: "Data Analyst with strong business focus",
        linkedin: "https://www.linkedin.com/in/manitra-rakotozafy-b83ba5a9/",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "4z34yb3f6lkcdf4z34y9r2telmk3t361",
        fullName: "Etienne P.",
        position: "Android Developer",
        experience: "> 10 years",
        tags: ["Kotlin", "Architecture", "Libraries"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction: "Mobile Lead dev and experienced Android dev",
        linkedin: "https://www.linkedin.com/in/etiennepinault/",
        github: "https://github.com/estebanpianolo",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "yy2oory96p80qzqwrus7rsyy2oorum0u",
        fullName: "Patrick P.",
        position: "Backend Developer",
        experience: "3 - 5 years",
        tags: ["Node.js", "Typescript", "MongoDB"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction: "Backend developer, mostly in Typescript",
        linkedin: "https://www.linkedin.com/in/patrick-portal-809302a8/",
        github: "https://github.com/patrickportal",
        personalWebsite: "http://patrickportal.ovh",
        department: "Engineering",
    },
    {
        id: "4hbw8eay8h7y67nidv6r4hbw8eayruvd",
        fullName: "Benoît B.",
        position: "Product Manager",
        experience: "5 - 10 years",
        tags: ["Product", "Mobile", "User oriented"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction:
            "Built Kapten's apps and services for 4 years. Love to build products for users with several teams involved and make them all look in the same direction 🚀",
        linkedin: "https://www.linkedin.com/in/benoitbaldo/",
        github: "",
        personalWebsite: "",
        department: "Product",
    },
    {
        id: "fev1y3bjvowm7jg4zfev1ymr14slxscc",
        fullName: "Mohamed J.",
        position: "Backend Developer",
        experience: "3 - 5 years",
        tags: ["Node.js", "Typescript", "Developer Experience"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "From providing internal tools / libraries for Kapten_ developers to build & deploy delightful features and contributing to the Payment domain, I believe in raising each other through candor & empathy in the workplace.",
        linkedin: "https://www.linkedin.com/in/mohamed-jeffal-8a68a8b7/",
        github: "https://github.com/MohamedJeffal",
        personalWebsite: "",
        department: "Engineering",
    },
    // {
    //     id: "dy33j76r8f8zn06n7damdy33t9czaf1k",
    //     fullName: "Maxime J.",
    //     position: "Backend Developer",
    //     experience: "3 - 5 years",
    //     tags: ["Node.js", "Typescript", "MongoDB"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: true,
    //     introduction:
    //         "Backend developer who likes teamwork and share knowledges to build resilient and scalable services.",
    //     linkedin: "https://www.linkedin.com/in/maxime-jimenez-874358116",
    //     github: "https://github.com/maximejimenez",
    //     personalWebsite: "",
    //     department: "Engineering",
    // },
    // {
    //     id: "hbhrebcpz4vz0zd8hbhretmdtrzlyvsd",
    //     fullName: "Gilles R.",
    //     position: "CTO",
    //     experience: "5 - 10 years",
    //     tags: ["Architecture", "Node.js", "Leadership"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: false,
    //     introduction:
    //         "Positive and enthusiastic engineer, I like to solve problems and learn new things every day.",
    //     linkedin: "https://www.linkedin.com/in/gillesrasigade/",
    //     github: "https://github.com/GillesRasigade",
    //     personalWebsite: "http://gillesrasigade.github.io/",
    //     department: "Engineering",
    // },
    {
        id: "r2huuhgnprigvcr2hu9h6r7jbeeb84n1",
        fullName: "Alexis V.",
        position: "Android Developer",
        experience: "> 10 years",
        tags: ["Kotlin", "Android", "Architecture"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Android lead dev. Product oriented. Love small and medium size companies.",
        linkedin: "https://www.linkedin.com/in/alexis-vapillon-7522873/",
        github: "https://github.com/alexisvapillon",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "322iknmtnv55jz9322iknkuc5qkuufbc",
        fullName: "Lucien N.",
        position: "Product Designer",
        experience: "0 - 1 year",
        tags: ["Design System", "UX", "Prototype"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "My goal is to design solutions that answer the best to the faced issues.",
        linkedin: "https://www.linkedin.com/in/lucien-noir-3388ab143/",
        github: "",
        personalWebsite: "http://www.luciennoir.fr/",
        department: "Product",
    },
    // {
    //     id: "y5e2mg6ba2qitg2fp8kog3y5e2mgwqkd",
    //     fullName: "Aksam N.",
    //     position: "Quality Analyst",
    //     experience: "5 - 10 years",
    //     tags: ["User centric", "Test plans/cases", "Critical thinking"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: true,
    //     introduction:
    //         "Lead QA with 8+ years of experience in fast-paced and agile startups with quick development life cycles.",
    //     linkedin: "https://www.linkedin.com/in/aksam-naisse/",
    //     github: "",
    //     personalWebsite: "",
    //     department: "Engineering",
    // },
    // {
    //     id: "qmbhlrxoiuobkqcqmbhlm6i9d0d3hqyj",
    //     fullName: "Louis E.",
    //     position: "IOS Developer",
    //     experience: "5 - 10 years",
    //     tags: ["IOS", "Reactive Programming", "Lead"],
    //     location: "Paris",
    //     isOpenToRelocationOrRemote: true,
    //     introduction: "Experienced iOS developer looking for a Lead/EM role",
    //     linkedin: "https://www.linkedin.com/in/louisencontre/",
    //     github: "https://github.com/AppsTitude",
    //     personalWebsite: "https://twitter.com/M_Plot",
    //     department: "Engineering",
    // },
    {
        id: "u0a0k4rubgg2da1pzxu0a0kfp63djewg",
        fullName: "Luca S.",
        position: "Backend Developer",
        experience: "3 - 5 years",
        tags: ["Python", "C++", "Node.js"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Experienced backend developer with 5 years of experience",
        linkedin: "https://www.linkedin.com/in/luca-savarino-296b5182/",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "wqa5ze538gcob0vqiwqa5ygo3sytaerc",
        fullName: "Boris L.",
        position: "Lead Developer",
        experience: "5 - 10 years",
        tags: ["Management", "TypeScript", "React"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction:
            "Technical lead specialised in frontend development. I like solving both technical and human problems.",
        linkedin: "https://www.linkedin.com/in/boris-lebon/",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "ggl7sgdhadsdahx9zjjggl7sgbbb24p8",
        fullName: "Julien J.",
        position: "Site Reliability Engineer",
        experience: "3 - 5 years",
        tags: ["GCP", "Kubernetes", "Terraform"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction:
            "Site Reliability Engineer with 5 years of experience in system and automation operations.",
        linkedin: "https://www.linkedin.com/in/julienjourdain/",
        github: "https://github.com/julienjourdain",
        personalWebsite: "https://jourdain.io",
        department: "Engineering",
    },
    {
        id: "2tn43wfg69tkr83eb5p2tn43wfg65ado",
        fullName: "Jean-Yves P",
        position: "Tribe Director",
        experience: "> 10 years",
        tags: ["Management", "Hiring", "Architecture"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "Building great product with great people in fast paced environments. Looking for a CTO or VP engineering position.",
        linkedin: "https://www.linkedin.com/in/jypoilleux/",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "ugn83sfcjmtixyq7ugn83y7ds94wr5wj",
        fullName: "Jérôme L.",
        position: "Databases Architect",
        experience: "> 10 years",
        tags: ["Architecture", "Databases", "Management"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction: "Databases Architect / Management",
        linkedin: "https://fr.linkedin.com/in/jerome-licciardello",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "4dj05uhx5xbwj644dj0qcax7zvqce1bv",
        fullName: "Pournima T",
        position: "Quality Analyst",
        experience: "> 10 years",
        tags: ["QA & QA Lead", "Automation Testing", "Java & Appium"],
        location: "Paris",
        isOpenToRelocationOrRemote: true,
        introduction:
            "10+ yrs of experience as a QA &  4+ yrs as QA Lead with ISTQB, PRINCE2 & CSM Certified. Worked on domains like OSS, BSS, BFSI, Travel, e-commerce etc.  Experience in testing API, web & mobile application, STB device testing, etc.",
        linkedin: "https://www.linkedin.com/in/pournimatele",
        github: "",
        personalWebsite: "",
        department: "Engineering",
    },
    {
        id: "tohtfgnrwnkvbnlnpv3tohtfgnnny37p",
        fullName: "Azelie Vericel",
        position: "HR Manager",
        experience: "5 - 10 years",
        tags: ["International HR", "Management", "Organisational development"],
        location: "Paris",
        isOpenToRelocationOrRemote: false,
        introduction:
            "HR manager with a proven expertise of 7 years on the field",
        linkedin:
            "https://www.linkedin.com/in/az%C3%A9lie-v%C3%A9ricel-015a03b8",
        github: "",
        personalWebsite: "",
        department: "Human Ressources",
    },
];
